theme: jekyll-theme-slate
title: welcome to the octocat's homepage!
descreption: feel free to bookmark this to keep an eye on my projects updates. this change is for to check how i can make changes into the subbranch and merge it with original.
